n = str(input("Digite o seu nome completo: ")).strip()
nome = n.split()
print("Muito prazer em conhecer!")
print("Seu primero nome é {}".format(nome[0]))
print("Seu ultimo nome é {}".format(nome[4]))
